ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: MYIP.sslip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ingress-tls
      hosts:
       - MYIP.sslip.io
neo4j:
  serviceName: ingress-haproxy-lb-neo4j
service:
  type: LoadBalancer