{{- with .Values.data }}
{{- if or .awsVolumeID .storageClassName -}}
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  # n.b. persistent volumes don't seem to belong to namespaces
  name: "{{ $.Release.Name }}"
  labels:
    type: aws-pv
    # the app name is used to link this persistent volume to the Neo4j StatefulSet
    app: "{{ template "neo4j.appName" $ }}"
    helm.neo4j.com/volume-role: "data"
spec:
  capacity:
    storage: "{{ required "data.capacity.storage must be set explicitly" .capacity.storage }}"
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "{{ required "data.awsVolumeID is required (e.g. my-disk)" .awsVolumeID }}"
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ .storageClassName }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $.Release.Name }}"
  labels:
    type: aws-pvc
    helm.neo4j.com/volume-role: "data"
    app: "{{ template "neo4j.appName" $ }}"
spec:
  storageClassName: "{{ .storageClassName }}"
  volumeName: "{{ $.Release.Name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ required "data.capacity.storage must be set explicitly" .capacity.storage }}"
  {{- end }}
  {{- end }}
