neo4jName: &neo4jName "ingress-haproxy"
neo4j-database-ingress:
  fullnameOverride: "dbingress"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: MYIP.sslip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ingress-tls
        hosts:
          - MYIP.sslip.io
  neo4j:
    service:
      name: db-server1
  service:
    type: LoadBalancer

db-server1:
  disableLookups: true
  fullnameOverride:  "db-server1"
  neo4j:
    name: *neo4jName
    acceptLicenseAgreement: "yes"
    edition: enterprise
    minimumClusterSize: 3
    passwordFromSecret: test-auth
  volumes:
    data:
      mode: defaultStorageClass
  services:
    neo4j:
      enabled: false
db-server2:
  disableLookups: true
  fullnameOverride: "db-server2"
  neo4j:
    name: *neo4jName
    acceptLicenseAgreement: "yes"
    edition: enterprise
    minimumClusterSize: 3
    passwordFromSecret: test-auth
  volumes:
    data:
      mode: defaultStorageClass
  services:
    neo4j:
      enabled: false
db-server3:
  disableLookups: true
  fullnameOverride: "db-server3"
  neo4j:
    name: *neo4jName
    acceptLicenseAgreement: "yes"
    edition: enterprise
    minimumClusterSize: 3
    passwordFromSecret: test-auth
  volumes:
    data:
      mode: defaultStorageClass
  services:
    neo4j:
      enabled: false