kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  name: neo4j-data-storage
  labels:
    type: local
    app: neo4j-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: neo4j
    name: neo4j-data-neo4j-db-0
  gcePersistentDisk:
    pdName: neo4j-data-disk