kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  name: neo4j-pv
  labels:
    app: neo4j
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: neo4j-data-disk
