kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  name: neo4j-data-storage
  labels:
    type: local
    app: neo4j-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: neo4j-data-disk