kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  name: neo4j-data-storage
  labels:
    type: local
    app: neo4j
spec:
  storageClassName: "neo4j-storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: neo4j
    name: data-neo4j-0
  gcePersistentDisk:
    pdName: neo4j-data-disk