name: Execute Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - bin/gcloud/*
      - internal/*
    branches:
      - dev

jobs:
  gke-setup:
    name: Execute enterprise tests
    runs-on: ubuntu-latest
    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
      CLOUDSDK_COMPUTE_ZONE: "europe-west2-b"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate Service Account
        run: |
          echo "CLOUDSDK_CONTAINER_CLUSTER=ghactions-$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          ./bin/gcloud/auth

      - name: Create GKE Cluster
        run: |
          ./bin/gcloud/create_cluster

      - name: Delete GKE Cluster
        run: |
          ./bin/gcloud/delete_cluster

#  run-enterprise-tests:
#    name: Execute enterprise tests
#    runs-on: ubuntu-latest
#    env:
#      NEO4J_EDITION: enterprise
#      NEO4J_DOCKER_IMG: "neo4j:5.16.0-enterprise"
#      GO_TEST_COUNT: 1
#      GO_TEST_TIMEOUT: 20m
#      GO_TEST_FORMAT: json
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BACKUP }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BACKUP }}
#    steps:
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: "{{defaultContext}}:build"
#          push: true
#          tags: neo4jbuildservice/helm-charts-tester:githubactions
